version: "3.8"

services:
  db:
    image: postgres:15
    container_name: desafio_sql_agent_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
